### ISSUE TITLE
Addition Moderation Commands

### ISSUE THREAD

**Issue by PrimeStrat** [EndstoneMC/endstone#104]
Since we have /ban /unban and /banlist - I wanted to make a request for some additional QoL moderation commands! Namely the essentials following:

/tempban - To temporarily ban a player
/mute - To permanently mute a player
/tempmute - To temporarily mute a player
/punishments - A means of checking punishment history or how long they have left on an applied punishment?

**Comment by smartcmd** [comment]
You can use /ability mute xxx false to mute a player

**Comment by PrimeStrat** [comment]
I'm aware- but it requires education edition to be enabled which some may not want. Furthermore, you cannot set a reason for the mute with /ability.

**Comment by wu-vincent** [comment]
Thank you for the suggestion. I believe these features are better suited to be implemented as custom plugins rather than being part of this project. Our primary focus is on providing the necessary APIs, allowing plugin developers to create such specific features.

That being said, I will ensure the ban API is made available to plugin developers soon.
