### ISSUE TITLE
[feature] Endstone should remove quotes from selector parameters

### ISSUE THREAD

**Issue by killcerr** [EndstoneMC/endstone#30]
**Describe the bug**

**To Reproduce**
The '"' should be removed

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
 - OS: windows
 - Endstone Version: v0.5.0

**Additional context**

**Comment by wu-vincent** [comment]
The problem should be rather easy to fix, but my concern is that it's hard to know when the quotes are intentional. I decided not to remove the quotes except for the selector types (e.g., `player` and `actor`) where quotes are apparently used for escaping spaces. For string parameters, it would be the plugin's responsibility to deal with the quotes.

**Comment by wu-vincent** [comment]
Finished in https://github.com/EndstoneMC/endstone/commit/6c8ec8d716e48d66ec0ba6156388324610f0a565
