### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by PrimeStrat** [EndstoneMC/endstone#49]
Output Log:

[2024-09-12 20:37:45.513 ERROR] [Server] Level corruption detected, disconnecting clients and shutting down server
=== ENDSTONE CRASHED! - PLEASE REPORT THIS AS AN ISSUE ON GITHUB ===
Operation system: Windows
Endstone version: 0.5.3
Api version     : 0.5
Description     : Exception unhandled: 0xc0000005
Stack trace (most recent call first):
#0  0x7ff92b1ab35f     (0x1800cb35f) in endstone::detail::`anonymous namespace'::exception_filter(_EXCEPTION_POINTERS*) at D:\a\endstone\endstone\src\endstone_runtime\windows\signal_handler.cpp:53
#1  0x7ff9a2d80bbb     (0x180160bbb) in UnhandledExceptionFilter
#2  0x7ff9a57996bc     (0x1800a96bc) in RtlCopyMemory
#3  0x7ff9a577f666     (0x18008f666) in __C_specific_handler
#4  0x7ff9a579504e     (0x1800a504e) in __chkstk
#5  0x7ff9a570e865     (0x18001e865) in RtlFindCharInUnicodeString
#6  0x7ff9a579403d     (0x1800a403d) in KiUserExceptionDispatcher
#7  0x7ff600f63937     (0x1400b3937) in  ??
#8  0x7ff601b12f4a     (0x140c62f4a) in  ??
#9  0x7ff6026e248d     (0x14183248d) in  ??
#10 0x7ff601ae6511     (0x140c36511) in  ??
#11 0x7ff601ad8ac5     (0x140c28ac5) in  ??
#12 0x7ff601a4ec1d     (0x140b9ec1d) in  ??
#13 0x7ff9a32f9332     (0x180029332) in _recalloc
#14 0x7ff9a45b257c     (0x18001257c) in BaseThreadInitThunk
#15 0x7ff9a574af27     (0x18005af27) in RtlUserThreadStart

**Comment by wu-vincent** [comment]
Thank you for reporting the issue. I've carefully reviewed the stack trace, and it appears this crash did not originate from Endstone. The crash occurred when BDS detected a level corruption, which then triggered an unhandled error that terminated the server. Endstone's crash handler captured this error, but the root cause lies with BDS itself.

If you believe this is a bug, I recommend reporting it directly to Mojang’s bug tracker.
