### ISSUE TITLE
[bug] event.block.type conversion error in blockplaceevent

### ISSUE THREAD

**Issue by pgrd1** [EndstoneMC/endstone#59]
**Describe the bug**
When you import a block from blockplaceevent, isn't it imported into event.block.type? Why does it always retrun minecraft:air

**To Reproduce**
Trigger blockplaceevent and output event.block.type

**Expected behavior**
Originally, the id of the installed block should come out

**Screenshots**

**Details (please complete the following information):**
 - OS: Windows
 - Endstone Version: last

**Additional context**

**Comment by wu-vincent** [comment]
It is a bit ambiguous here that the property actually represents the block getting replaced. To get the block to be placed, use the "block_placed_state" property. 

We design it like this because the event is called before the block is actually placed into the world. So there is no way to get an instance of the block to be placed, instead you can only get a state that will be set to the block if the event is not cancelled.
