### ISSUE TITLE
Server-side anticheat

### ISSUE THREAD

**Issue by BbayuGt** [EndstoneMC/endstone#85]
**Is your feature request related to a problem? Please describe.**
Yes, the feature is related to cheating problems

**Describe the solution you'd like**
As you know, bedrock server have no kind of validation (at least something that i know), so you can use third party application to just give yourself an item, fly, god mode, etc etc. can we have better checking on how the player get the item, how much HP does he have, can he actually fly?, etc. It needs at least just the basic one (item, hp, flying, speed hacks).

**Describe alternatives you've considered**
probably third party plugins in the future, but this checks should be there out of the box.

**Additional context**
-

**Comment by xXLarryTFVWXx** [comment]
I believe that one can manually edit these in the server.properties file next to the BDS exe.

**Comment by syylaxx** [comment]
Well this is pretty a pretty outdated info.

You cannot anymore give yourself items since it is only server-wise.
Almost everyting else can be validated by setting some variables to `true` (or the relative value) in `server.properties`
```properties
server-authoritative-movement=server-auth-with-rewind
# Allowed values: "client-auth", "server-auth", "server-auth-with-rewind"
# Changes the server authority on movement:
# "client-auth": Server has no authority and accepts all positions from the client.
# "server-auth": Server takes user input and simulates the Player movement but accepts the Client version if there is disagreement.
# "server-auth-with-rewind": The server will replay local user input and will push it to the Client so it can correct the position if it does not match.
# The clients will rewind time back to the correction time, apply the correction, then replay all the player's inputs since then. This results in smoother and more frequent corrections.

server-authoritative-block-breaking-pick-range-scalar=true
# If true, the server will compute block mining operations in sync with the client so it can verify that the client should be able to break blocks when it thinks it can.

client-side-chunk-generation-enabled=true
# If true, the server will inform clients that they have the ability to generate visual level chunks outside of player interaction distances.

server-build-radius-ratio=Disabled
# Allowed values: "Disabled" or any value in range [0.0, 1.0]
# If "Disabled" the server will dynamically calculate how much of the player's view it will generate, assigning the rest to the client to build.
# Otherwise from the overridden ratio tell the server how much of the player's view to generate, disregarding client hardware capability.
# Only valid if client-side-chunk-generation-enabled is enabled
```
these are all the variables that set some features server-wise

Some of them bug, especially on linux.
I would prefer using addons as the primary anticheat instead.

**Comment by xXLarryTFVWXx** [comment]
@syylaxx Thank you!  This is what I was thinking of!

**Comment by BbayuGt** [comment]
So some of them are bugged, do you have any recommendations of what should i use as my anti cheat (if any)? Endstone is pretty new so its kinda hard to find a recommendation

**Comment by syylaxx** [comment]
> @BbayuGt 

Well yes they are bugged and rely on Internet more.
But this is the best anticheat you could use.

If you want a alternative use addons. Since they are more powerful than the current Endstone API.
I cant really give you a recommendation, because i code every plugin and addon by myself but you can search for one in either Addon Discord or Internet.

Also i dont think that a AntiCheat written using Endstone API exists. Atleast it isnt present in the discord forum or [Bedrinth](https://bedrinth.com/?q=endstone) website

> "... you mean addon anticheat, is it really that powerful?"

Addons can be overall powerful, but cheats in Bedrock arent that advanced. Most of them just use velocity spikes, so it is very easy to detect. The rest can be detected by math or in any other way, depends.

**Comment by wu-vincent** [comment]
Thank you to everyone involved in this discussion—there’s been a lot of useful information shared. I'll be closing the issue as it’s currently not a goal of this project. However, I’ve added the "good first issue" tag so it’s easier for others who come across this question in the future.
